config/routes.rb
Rails.application.routes.draw do
  get 'user_tareas/create'
  resources :tareas, only: :show do
    resources :user_tareas, only: [:destroy]
end

  resources :tareas, only: :index do
    
    resources :user_tareas, only: :create #ruta rest
    
end


  
resources :user_tareas, only: :index


  root to: 'tareas#index' #pag principal
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarea.rb
class Tarea < ApplicationRecord
    has_many :user_tareas
    has_many :users, through: :user_tareas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_tareas
  has_many :tareas, through: :user_tareas       
end

app/models/user_tarea.rb
class UserTarea < ApplicationRecord
  belongs_to :user
  belongs_to :tarea
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  

  def index
    @tareas = Tarea.all
  end

  def show
    @tarea = Tarea.find(params[:id])
    @users = @tarea.users
    @tareas_realizadas = @tarea.user_tareas.order(:created_at).limit(5)  
  end

end

app/controllers/user_tareas_controller.rb
class UserTareasController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @tarea = Tarea.find(params[:tarea_id])
    @user_tarea = UserTarea.new(tarea: @tarea, user: current_user)
    if @user_tarea.save
        redirect_to tareas_path, notice: 'Tarea completada'
    else
        redirect_to tareas_path, alert: 'Esta Tarea aún no ha sido completada'
    end    
  end

  def index
     @user_tareas = current_user.user_tareas

  end

  

  def destroy
    @tarea = Tarea.find(params[:tarea_id])
    @user_tarea = UserTarea.where(tarea: @tarea, user: current_user)
    if @user_tarea.first.destroy
       redirect_to tareas_path, alert: 'Esta Tarea aún no ha sido completada'
    else
       redirect_to tareas_path, notice: 'Tarea completada'
    end 
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/user_tareas_helper.rb
module UserTareasHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Lista para el 18</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= tareas_path %>">Lista de Tareas <span class="sr-only">(current)</span></a>
      </li>
      
      <% if current_user%>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_tareas_path %>"> Mis Tareas Completadas <strong><%= current_user.user_tareas.count %>/9 </strong> </a>
      </li>
    </ul>


    <ul class="navbar-nav mr-auto">    
        <li class="nav-item">
            <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
          
    
      <% else %>
        <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, method: :get, class: 'nav-link' %>
        </li>

        <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, method: :get, class: 'nav-link' %>
        </li>
      <% end %>  
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoListApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
         <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
         <%= alert %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/tareas/index.html.erb
<div class="container">
    <div class="row">
        <% @tareas.each_slice(3) do |row| %>
            <% row.each do |tarea| %>
                <div class="col">
                    <div class="card">
                        <%= image_tag tarea.foto, class: 'card-img-top' %>
                            

                        
                        <div class="body">   
                            <h4> <%= tarea.nombre %> </h4>
                            
                            <% if current_user %>
                            <%= link_to "NO listo", tarea_user_tarea_path(tarea, current_user), class: 'btn btn-danger', method: 
                                :delete %>
                                

                            <%= link_to "Listo", tarea_user_tareas_path(tarea), class: 'btn btn-success', method: :post %>
                            <% end %>
                           
                            <%= link_to "Ver detalle", tarea_path(tarea), class: 'btn btn-success', method: :GET %>




                        </div>    
                        
                    </div>    
                </div>    
            <% end %>
            <div class="w-100" style="margin-top: 40px"> </div>
        <% end %>    
    </div>
</div>

app/views/tareas/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <h4><%= @tarea.nombre %></h4>
                </thead>    
                    <% @users.each do |user|%>
                    <tr>
                        <td> Nombre: <%= user.first_name%></td>
                    </tr>

                    <tr>
                        <td> Apellido: <%= user.last_name%></td>
                    </tr>

                    <tr>
                        <td> Email Usuario: <%= user.email%></td>
                    </tr>
                    <tr>
                        <td> Fecha Creación: <%= user.created_at%></td>
                    </tr>



                    <% end %>

                
            </table>    
        </div>    
            
        <div class="col-md-6">    
                <%= image_tag @tarea.foto, class: 'card-img-top' %>
        </div>    
            
            
        </div>    
    </div>    
</div>

app/views/user_tareas/create.html.erb
<h1>UserTareas#create</h1>
<p>Find me in app/views/user_tareas/create.html.erb</p>

app/views/user_tareas/index.html.erb
<table class="table">
    <% @user_tareas.each do |resumentarea| %>
        <tr>
            <td> <%= resumentarea.tarea.nombre %> </td>
        </tr>
    <% end %>
</table>